---

sts: special
  become: true
  tasks:
   - name: Installs Apache HTTP server
     apt: pkg={{ item }} state=present update_cache=yes
     with_items:
      - apache2
      - wget
      - vim
      - tree

     notify:
      - start-apache

   - name: Copy Web sites to nodes
     copy: src=~/infotern/ dest=/var/www/html/ owner=root group=root mode=0644
     notify:
       - restart-apache

  handlers:
    - name: start-apache
      service: name=apache2 state=started


- hosts: special
  become: true
  tasks: 
   - name: Installs Apache HTTP server
     apt: pkg={{ item }} state=present update_cache=yes
     with_items:
      - apache2
      - wget
      - vim
      - tree
   
     notify:
      - start-apache

   - name: Copy Web sites to nodes
     copy: src=~/infotern/ dest=/var/www/html/ owner=root group=root mode=0644
     notify:
       - restart-apache

  handlers:
    - name: start-apache
      service: name=apache2 state=started 
      
    - name: restart-apache
      service: name=apache2 state=restarted 


