---
- hosts: special
  become: true
  tasks:
   - name: Installs Apache HTTP server
     yum: pkg={{ item }} state=present update_cache=yes
     with_items:
      - nginx
      - wget
      - vim
      - tree

     notify:
      - start-nginx

   - name: Copy Web sites to nodes
     copy: src=~/infotern/ dest=/usr/share/nginx/html/ owner=root group=root mode=0644
     notify:
       - restart-nginx

  handlers:
    - name: start-nginx
      service: name=nginx state=started

    - name: restart-nginx
      service: name=nginx state=restarted

